In [4]:
#NUMPY operations
#Exercise Sheet 2

[0 1 2 3]


In [6]:
#Assign to the ‘’a’’ variable a NumPy array containing this list: 1, 2, 3
#Assign to the ‘’c’’ variable a NumPy array containing these lists: 1, 2, 3 and 4, 5, 6
#Display the shape of ‘’c’’

import numpy as np
a = np.arange(4)
print(a)

c = np.array(([1,2,3,], [4,5,6]))
print(c)

c.shape

[0 1 2 3]
[[1 2 3]
 [4 5 6]]


(2, 3)

In [7]:
#Display a NumPy array having values from 0 to 11 with a step of 1 on 3 rows and 4 columns
#Display a NumPy array having values from 3 to 75 with a step of 3 having 4 values on axis 0, 3 on
#axis 1, and 2 on axis 2

arr1 = np.arange(0,12).reshape(3,4)
print(arr1)

arr1 = np.arange(3,75,3).reshape(4,3,2)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 3  6]
  [ 9 12]
  [15 18]]

 [[21 24]
  [27 30]
  [33 36]]

 [[39 42]
  [45 48]
  [51 54]]

 [[57 60]
  [63 66]
  [69 72]]]


In [8]:
#Display a 1D NumPy array having 3 random values
#Display a 2D NumPy array having 3 random values on each dimension

arr1 = np.random.random(3)
print(arr1)

arr1 = np.random.random((3,3))
print(arr1)

[0.23433613 0.44979952 0.85117776]
[[0.09086268 0.72187497 0.48789183]
 [0.55779018 0.36484195 0.80319062]
 [0.18216481 0.64820195 0.09054973]]


In [12]:
#Create a list filled with the following values: 1, 2, 3, 4, 5, 6.
#Transform the list to an array called arr1
#Compute the mean, median, and standard deviation using NumPy

lst = [1, 2, 3, 4, 5, 6]

arr1 = np.array(lst)
print(arr1)

print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))

[1 2 3 4 5 6]
3.5
3.5
1.707825127659933


In [15]:
#Create a list filled with the following values: 100, 200, 300, 400, 500, 600.
#Transform the list to an array called arr2

lst1 = [100, 200, 300, 400, 500, 600]

arr2 = np.array(lst1)
print(arr2)

[100 200 300 400 500 600]


In [16]:
#-Compute the covariance and the correlation of arr1 & arr2 

np.cov(arr1,arr2)
np.corrcoef(arr1,arr2)

array([[1., 1.],
       [1., 1.]])

In [17]:
#-Write a program to check the NumPy version installed on your machine
print(np.__version__)

1.24.3
