In [2]:
#This was a Python Exam we completed in class, it shows some of the skills I have learnt in Python.

Where were you born?
This person was born in 


In [ ]:
#EX1

birthplVal = input('Where were you born?')
print('This person was born in ' + birthplVal)

In [3]:
#EX2

tmpLst = []
n = 10
while n >= 5:
    tmpLst.append(n)
    n = n - 1

In [4]:
tmpLst

[10, 9, 8, 7, 6, 5]

In [5]:
for cpt in range(len(tmpLst)):
    print(tmpLst[cpt])

10
9
8
7
6
5


In [6]:
for elt in tmpLst:
    print(elt)

10
9
8
7
6
5


In [26]:
#EX3

prodDict = {'Product A' : [10.99, 50], 
           'Product B' : [5.99, 30],
           'Product C' : [7.49, 25]}

prodDict


{'Product A': [10.99, 50], 'Product B': [5.99, 30], 'Product C': [7.49, 25]}

In [27]:
totRev = 0
for keyElt in prodDict.keys():
    totRev += prodDict[keyElt][0] * prodDict[keyElt][1]
    print(keyElt + 'revenue is ' + str(prodDict[keyElt][0] *
                                     prodDict[keyElt][1]))

Product Arevenue is 549.5
Product Brevenue is 179.70000000000002
Product Crevenue is 187.25


In [28]:
print('The toal revenue is ' + str(totRev))

The toal revenue is 916.45


In [29]:
import pandas as pd

In [30]:
#Convert to pandas

prodDf = pd.DataFrame(prodDict)

In [31]:
prodDf

Product A  Product B  Product C
0      10.99       5.99       7.49
1      50.00      30.00      25.00

In [32]:
prodDf.set_index([['Cost','Quantity']], inplace=True)

In [33]:
prodDf

Product A  Product B  Product C
Cost          10.99       5.99       7.49
Quantity      50.00      30.00      25.00

In [34]:
prodDf.iloc[1,2] = 35

In [36]:
prodDf.loc['Quantity', 'Product B'] = 45

In [37]:
prodDf

Product A  Product B  Product C
Cost          10.99       5.99       7.49
Quantity      50.00      45.00      35.00

In [38]:
#EX4

from scipy import stats

In [43]:
#Create a 'MeanFun' function to compute the average of a list

def MeanFun(l):
    return(sum(l)/len(l))

In [44]:
lst = [2,4,6,8,10]

In [45]:
MeanFun(lst)

6.0

In [46]:
#Create a 'Beta1Fun' function to compute the coeffecient of 2 lists

a = [12, 15, 6, 13, 12, 18, 2, 15, 8, 9, 16, 14, 16]
b = [-12, -15, -6, -13, -12, -18, -2, -16, -8, -9, -16, -14, -16]

In [47]:
def Beta1Fun(la, lb):
    if len(la) == len(lb):
        sumNum = 0
        sumDen = 0
        for i in range(len(la)):
            sumNum += (la[i] - MeanFun(la)) * (lb[i] - MeanFun(lb))
            sumDen += (la[i] - MeanFun(la)) * (la[i] - MeanFun(la))
        return(sumNum / sumDen)


In [48]:
print(Beta1Fun(a, b))

-1.0119047619047619


In [49]:
print(stats.linregress(a, b).slope)

-1.0119047619047619


In [50]:
#EX5

inpPath = '/Users/emsfl/Downloads/'

In [53]:
inpDf = pd.read_csv(inpPath + 'Assignment_Input.csv', delimiter=',', header=0, index_col=None)

In [54]:
inpDf

AdvBudg  Sales
0     1000   3200
1     2000   4500
2     3000   6100
3     4000   7800
4     5000   9200
5     6000  11500
6     7000  13300
7     8000  15700
8     9000  17900
9    10000  20100

In [55]:
beta1Val = Beta1Fun(inpDf['AdvBudg'], inpDf['Sales'])

In [59]:
beta1Val

1.8951515151515153

In [60]:
beta0Val = inpDf['Sales'].mean() - beta1Val * inpDf['AdvBudg'].mean()

In [61]:
beta0Val

506.66666666666606

In [62]:
yPredVal = beta0Val + beta1Val * 15000

In [63]:
yPredVal

28933.939393939392

In [64]:
#EX6

import numpy as np

In [67]:
np.arange(105, 195, 5).reshape(3,6)

array([[105, 110, 115, 120, 125, 130],
       [135, 140, 145, 150, 155, 160],
       [165, 170, 175, 180, 185, 190]])

In [68]:
list = [3, 4, 5, 6, 7, 8]

In [70]:
arr1 = np.array(list)

In [71]:
arr1

array([3, 4, 5, 6, 7, 8])

In [72]:
np.mean(arr1)

5.5

In [73]:
np.median(arr1)

5.5

In [74]:
np.std(arr1)

1.707825127659933

In [76]:
#ZSCORE
print((arr1 - np.mean(arr1)) / np.std(arr1))

#is the list minus the mean then divide by the standard deviation

[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
